/* ============================================================
   SikBodo — service worker
   GENERATED by tools/build-pwa.mjs — do not edit by hand.
   Version 1.4.0

   Strategy
     • the app shell is precached, so the installed app opens and
       works with no network at all
     • version.json is network-first, so an update check always
       asks the server rather than the cache
     • everything else is cache-first, and refreshed in the
       background when a new worker takes over
   ============================================================ */

const VERSION = "1.4.0";
const CACHE = "sikbodo-" + VERSION;

const PRECACHE = [
  "./assets/splash-logo.svg",
  "./js/core/splash.js",
  "",
  "./404.html",
  "./about.html",
  "./assets/apple-touch-icon.png",
  "./assets/apsides-labs.svg",
  "./assets/favicon.svg",
  "./assets/icon-192.png",
  "./assets/icon-512.png",
  "./assets/icon-maskable-512.png",
  "./assets/icon-maskable.svg",
  "./assets/icons.svg",
  "./assets/logo-mark.svg",
  "./assets/logo.svg",
  "./assets/og-cover.svg",
  "./contribute.html",
  "./conversations.html",
  "./css/components.css",
  "./css/layout.css",
  "./css/motion.css",
  "./css/print.css",
  "./css/tokens.css",
  "./culture.html",
  "./dictionary.html",
  "./grammar.html",
  "./idioms.html",
  "./index.html",
  "./js/app.js",
  "./js/core/icons.js",
  "./js/core/install.js",
  "./js/core/prefs.js",
  "./js/core/store.js",
  "./js/core/update.js",
  "./js/data/contribute.js",
  "./js/data/culture.js",
  "./js/data/dialogues.js",
  "./js/data/dictionary.js",
  "./js/data/grammar.js",
  "./js/data/idioms.js",
  "./js/data/index.js",
  "./js/data/lessons.js",
  "./js/data/meta.js",
  "./js/data/numbers.js",
  "./js/data/phrases.js",
  "./js/data/reading.js",
  "./js/data/resources.js",
  "./js/data/script.js",
  "./js/data/verbs.js",
  "./js/render/interactive.js",
  "./js/render/renderers.js",
  "./js/ui/chrome.js",
  "./js/ui/mobilenav.js",
  "./js/ui/motion.js",
  "./js/ui/panel.js",
  "./js/ui/sidebar.js",
  "./js/ui/toc.js",
  "./lessons.html",
  "./manifest.webmanifest",
  "./metadata.json",
  "./numbers.html",
  "./package.json",
  "./phrases.html",
  "./progress.html",
  "./quiz.html",
  "./reading.html",
  "./resources.html",
  "./robots.txt",
  "./script.html",
  "./server.js",
  "./sitemap.xml",
  "./translator.html",
  "./verbs.html",
  "./version.json"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      // addAll rejects the whole install if one entry 404s, so add
      // each entry on its own and let a stray miss pass
      Promise.all(
        PRECACHE.map((url) =>
          cache.add(new Request(url, { cache: "reload" })).catch(() => {})
        )
      )
    )
  );
  // deliberately no skipWaiting: the running page decides when to swap
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys.filter((k) => k.startsWith("luitra-") && k !== CACHE).map((k) => caches.delete(k))
        )
      )
      .then(() => self.clients.claim())
  );
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") self.skipWaiting();
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // the update check must never be answered from cache
  if (url.pathname.endsWith("/version.json")) {
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
          return res;
        })
        .catch(() => caches.match(req))
    );
    return;
  }

  // navigations: cache first (offline), network as the fallback
  if (req.mode === "navigate") {
    event.respondWith(
      caches.match(req).then(
        (hit) =>
          hit ||
          fetch(req)
            .then((res) => {
              const copy = res.clone();
              caches.open(CACHE).then((c) => c.put(req, copy));
              return res;
            })
            .catch(() => caches.match("./index.html"))
      )
    );
    return;
  }

  // everything else: cache first, then network
  event.respondWith(
    caches.match(req).then((hit) => {
      if (hit) return hit;
      return fetch(req).then((res) => {
        if (res && res.status === 200 && res.type === "basic") {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
        }
        return res;
      });
    })
  );
});
