#!/usr/bin/env node
/* ============================================================
   SikBodo — PWA build step
   Reads the version from js/data/meta.js and writes:

     version.json   the file the running app polls to find out
                    whether a newer release exists
     sw.js          the service worker, with a cache name derived
                    from that same version and a precache list
                    built from what is actually on disk

   Run after changing the version or adding/removing files:

     node tools/build-pwa.mjs

   Both outputs are committed. Nothing here runs in the browser.
   ============================================================ */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

/* ---------- version, read from the single source of truth ---------- */

const meta = fs.readFileSync(path.join(ROOT, "js/data/meta.js"), "utf8");
const pick = (key) => {
  const m = meta.match(new RegExp(`"${key}"\\s*:\\s*"([^"]+)"`));
  if (!m) throw new Error(`Could not read "${key}" from js/data/meta.js`);
  return m[1];
};

const version = pick("version");
const released = pick("released");
const repo = pick("repo");

/* ---------- version.json ---------- */

const versionJson = {
  name: "SikBodo",
  version,
  released,
  notes: `${repo}/releases/tag/v${version}`,
};
fs.writeFileSync(
  path.join(ROOT, "version.json"),
  JSON.stringify(versionJson, null, 2) + "\n"
);

/* ---------- precache list ---------- */

const SKIP_DIRS = new Set([".git", ".github", "docs", "tools", "node_modules"]);
const KEEP = /\.(html|css|js|mjs|svg|png|webmanifest|json|txt|xml)$/i;

function walk(dir, base = "") {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith(".") && entry.name !== ".nojekyll") continue;
    const rel = base ? `${base}/${entry.name}` : entry.name;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      out.push(...walk(full, rel));
    } else if (KEEP.test(entry.name)) {
      out.push(rel);
    }
  }
  return out;
}

// everything the app needs to run offline, minus the worker itself
const assets = walk(ROOT)
  .filter((f) => f !== "sw.js" && !f.startsWith("docs/") && !f.startsWith("tools/"))
  .sort();

const list = ["", ...assets.map((f) => "./" + f)]; // "" === the directory root

/* ---------- sw.js ---------- */

const sw = `/* ============================================================
   SikBodo — service worker
   GENERATED by tools/build-pwa.mjs — do not edit by hand.
   Version ${version} · ${assets.length} precached entries

   Strategy
     • the app shell is precached, so the installed app opens and
       works with no network at all
     • version.json is network-first, so an update check always
       asks the server rather than the cache
     • everything else is cache-first, and refreshed in the
       background when a new worker takes over
   ============================================================ */

const VERSION = "${version}";
const CACHE = "luitra-" + VERSION;

const PRECACHE = ${JSON.stringify(list, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      // addAll rejects the whole install if one entry 404s, so add
      // each entry on its own and let a stray miss pass
      Promise.all(
        PRECACHE.map((url) =>
          cache.add(new Request(url, { cache: "reload" })).catch(() => {})
        )
      )
    )
  );
  // deliberately no skipWaiting: the running page decides when to swap
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys.filter((k) => k.startsWith("luitra-") && k !== CACHE).map((k) => caches.delete(k))
        )
      )
      .then(() => self.clients.claim())
  );
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") self.skipWaiting();
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // the update check must never be answered from cache
  if (url.pathname.endsWith("/version.json")) {
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
          return res;
        })
        .catch(() => caches.match(req))
    );
    return;
  }

  // navigations: cache first (offline), network as the fallback
  if (req.mode === "navigate") {
    event.respondWith(
      caches.match(req).then(
        (hit) =>
          hit ||
          fetch(req)
            .then((res) => {
              const copy = res.clone();
              caches.open(CACHE).then((c) => c.put(req, copy));
              return res;
            })
            .catch(() => caches.match("./index.html"))
      )
    );
    return;
  }

  // everything else: cache first, then network
  event.respondWith(
    caches.match(req).then((hit) => {
      if (hit) return hit;
      return fetch(req).then((res) => {
        if (res && res.status === 200 && res.type === "basic") {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
        }
        return res;
      });
    })
  );
});
`;

fs.writeFileSync(path.join(ROOT, "sw.js"), sw);

console.log(`build-pwa: version.json → ${version} (released ${released})`);
console.log(`build-pwa: sw.js → cache "luitra-${version}", ${assets.length} precached entries`);
